# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 581)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 581))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 581))
        MainWindow.setStyleSheet("\n"
"background-color:#faf8f6;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 900, 70))
        self.label.setStyleSheet("color:#056cc4;\n"
"font: 75 30pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(34, 210, 221, 41))
        self.label_2.setStyleSheet("font: 75 12pt \"Tahoma\";\n"
"border:none;\n"
"color:white;\n"
"background:none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(407, 410, 220, 41))
        self.label_3.setStyleSheet("color:white;\n"
"font: 75 12pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(716, 201, 240, 41))
        self.label_4.setStyleSheet("color:white;\n"
"font: 75 12pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(790, 510, 91, 31))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #056cc4, stop:1 #056cc4);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:5px;")
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 210, 250, 151))
        self.label_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0048a7, stop:1 #056cc4);\n"
" border-radius: 5px ;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(375, 390, 250, 151))
        self.label_9.setStyleSheet("background-color:#ed5d58;\n"
" border-radius: 5px ;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(700, 200, 270, 151))
        self.label_10.setStyleSheet(" border-radius: 5px ;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #0048a7, stop:1 #056cc4);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(322, 118, 341, 271))
        self.label_11.setStyleSheet("background:none;")
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("src/healthcare.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(88, 240, 115, 31))
        self.label_12.setStyleSheet("color:white;\n"
"font: 75 12pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(437, 440, 115, 31))
        self.label_13.setStyleSheet("\n"
"color:white;\n"
"font: 75 12pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(770, 231, 115, 31))
        self.label_14.setStyleSheet("\n"
"color:white;\n"
"font: 75 12pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(34, 303, 221, 51))
        self.lineEdit.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:5px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(387, 484, 221, 51))
        self.lineEdit_2.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:5px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(724, 292, 221, 51))
        self.lineEdit_3.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:5px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_10.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "May You Have The Following Disease"))
        self.label_2.setText(_translate("MainWindow", "Using Decision Tree Algo"))
        self.label_3.setText(_translate("MainWindow", "Using Naive Bayes Algo"))
        self.label_4.setText(_translate("MainWindow", "Using Random Forest Algo U may Have"))
        self.pushButton.setText(_translate("MainWindow", "Next"))
        self.label_12.setText(_translate("MainWindow", "U may Have "))
        self.label_13.setText(_translate("MainWindow", "U may Have "))
        self.label_14.setText(_translate("MainWindow", "U may Have"))
import src


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
