# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_4(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 670)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 670))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 670))
        MainWindow.setStyleSheet("\n"
"background-color:#f8fafb;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(339, 128, 611, 81))
        self.label.setStyleSheet("font: 75 32pt \"Tahoma\";\n"
"border:none;\n"
"background:none;\n"
"color:#012c6b;")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(339, 80, 711, 51))
        self.label_4.setStyleSheet("font: 75 32pt \"Tahoma\";\n"
"border:none;\n"
"background:none;\n"
"color:#012c6b;")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(349, 219, 703, 41))
        self.label_6.setStyleSheet("font: 10.5pt \"Tahoma\";\n"
"border:none;\n"
"background:none;\n"
"color:#d14452;")
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(50, 46, 271, 331))
        self.label_11.setStyleSheet("background:none;")
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("src/gfx-c.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(347, 240, 331, 41))
        self.label_7.setStyleSheet("color:#d14452;\n"
"font: 10.5pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_7.setObjectName("label_7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(357, 334, 221, 41))
        self.lineEdit.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:5px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(472, 407, 51, 51))
        self.label_13.setStyleSheet("background:none;")
        self.label_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("src/body-scan.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(360, 304, 231, 31))
        self.label_9.setStyleSheet("font: 10.5pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(458, 457, 111, 31))
        self.label_10.setStyleSheet("font: 10.5pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(743, 457, 111, 31))
        self.label_14.setStyleSheet("font: 10.5pt \"Tahoma\";\n"
"border:none;\n"
"background:none;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(752, 406, 51, 51))
        self.label_15.setStyleSheet("background:none;")
        self.label_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("src/health-check.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(100, 40, 921, 451))
        self.label_16.setMinimumSize(QtCore.QSize(921, 451))
        self.label_16.setMaximumSize(QtCore.QSize(921, 451))
        self.label_16.setStyleSheet("background:none;")
        self.label_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("src/shape.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(370, 490, 211, 31))
        self.plainTextEdit.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:2px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(648, 487, 241, 101))
        self.plainTextEdit_2.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:2px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(370, 550, 211, 31))
        self.plainTextEdit_3.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:2px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.plainTextEdit_3.setReadOnly(True)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setEnabled(True)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(370, 520, 211, 31))
        self.plainTextEdit_4.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:2px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.plainTextEdit_4.setReadOnly(True)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(370, 580, 211, 31))
        self.plainTextEdit_5.setStyleSheet("border: 1px solid #b3caff;\n"
"border-radius:2px;\n"
"background:none;\n"
"font:  \"Tahoma\";")
        self.plainTextEdit_5.setReadOnly(True)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.read = QtWidgets.QPushButton(self.centralwidget)
        self.read.setGeometry(QtCore.QRect(890, 610, 131, 31))
        self.read.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ed5d58, stop:1 #ed5d58);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-radius:5px;")
        self.read.setObjectName("read")
        self.label_16.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_6.raise_()
        self.label_11.raise_()
        self.label_7.raise_()
        self.lineEdit.raise_()
        self.label_13.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.plainTextEdit.raise_()
        self.plainTextEdit_2.raise_()
        self.plainTextEdit_3.raise_()
        self.plainTextEdit_4.raise_()
        self.plainTextEdit_5.raise_()
        self.read.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "for you and your family"))
        self.label_4.setText(_translate("MainWindow", "Healthcare ChatBot solutions"))
        self.label_6.setText(_translate("MainWindow", "Get professional advice anytime. Forget the pointless online health-related searches"))
        self.label_7.setText(_translate("MainWindow", " and long wait times at the doctor’s."))
        self.label_9.setText(_translate("MainWindow", "As a whole you Might Have"))
        self.label_10.setText(_translate("MainWindow", "Precaution"))
        self.label_14.setText(_translate("MainWindow", "Description"))
        self.read.setText(_translate("MainWindow", "Read"))
import src


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_4()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
